name: Build Backend

on:
  push:
    paths: "src/**"
  workflow_dispatch:

jobs:
  build:
    defaults:
      run:
        working-directory: src
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8 # oder deine gewünschte Version

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install Packages
        run: pnpm install

      - name: Generate Prisma Client
        run: pnpm prisma generate

      - name: Build
        run: pnpm run build
